export const AuditAction = {
  AUTH_LOGIN_SUCCEEDED: 'AUTH_LOGIN_SUCCEEDED',
  AUTH_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUTH_REFRESH_TOKEN_REUSED: 'AUTH_REFRESH_TOKEN_REUSED',

  ACCESS_DENIED: 'ACCESS_DENIED',

  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_STATUS_CHANGED: 'USER_STATUS_CHANGED',
  USER_UNLOCKED: 'USER_UNLOCKED',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  USER_DELETED: 'USER_DELETED',
  USER_ROLES_CHANGED: 'USER_ROLES_CHANGED',
  USER_PRIVILEGE_GRANTED: 'USER_PRIVILEGE_GRANTED',
  USER_PRIVILEGE_REVOKED: 'USER_PRIVILEGE_REVOKED',

  ROLE_CREATED: 'ROLE_CREATED',
  ROLE_UPDATED: 'ROLE_UPDATED',
  ROLE_PERMISSIONS_CHANGED: 'ROLE_PERMISSIONS_CHANGED',
  ROLE_PARENTS_CHANGED: 'ROLE_PARENTS_CHANGED',
  ROLE_DELETED: 'ROLE_DELETED',

  SAMPLING_POINT_CREATED: 'SAMPLING_POINT_CREATED',
  SAMPLING_POINT_UPDATED: 'SAMPLING_POINT_UPDATED',
  SAMPLING_POINT_DELETED: 'SAMPLING_POINT_DELETED',
  PARAMETER_CREATED: 'PARAMETER_CREATED',
  PARAMETER_UPDATED: 'PARAMETER_UPDATED',
  PARAMETER_DELETED: 'PARAMETER_DELETED',
  SAMPLE_CREATED: 'SAMPLE_CREATED',
  SAMPLE_UPDATED: 'SAMPLE_UPDATED',
  SAMPLE_DELETED: 'SAMPLE_DELETED',
  RESULTS_ENTERED: 'RESULTS_ENTERED',
  SAMPLE_SUBMITTED: 'SAMPLE_SUBMITTED',
  SAMPLE_VALIDATED: 'SAMPLE_VALIDATED',
  SAMPLE_REJECTED: 'SAMPLE_REJECTED',
  REPORT_EXPORTED: 'REPORT_EXPORTED',
} as const;

export type AuditAction = (typeof AuditAction)[keyof typeof AuditAction];
